kind: pipeline
name: default

workspace:
  base: /go
  path: src/p83.nl/go/ekster

steps:
  - name: testing
    image: golang:1.12-alpine
    commands:
      - export GOPATH=/go
      - export CGO_ENABLED=0 GOOS=linux GOARCH=amd64
      - apk --no-cache add git
      - go get -d -t ./...
      - go build ./...
      - go test ./...

  - name: publish-personal
    image: plugins/docker
    settings:
      repo: registry.stuifzandapp.com/microsub-server
      registry: registry.stuifzandapp.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # - name: publish-docker
  #   image: plugins/docker
  #   settings:
  #     repo: pstuifzand/ekster
  #     tags:
  #       - alpine
  #     dockerfile: Dockerfile.alpine
  #     username:
  #       from_secret: docker_official_username
  #     password:
  #       from_secret: docker_official_password

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: microsub.stuifzandapp.com
      username: microsub
      ssh_key:
        from_secret: ssh_key
      script:
        - cd /home/microsub/microsub
        - docker-compose pull web
        - docker-compose up -d
