# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-added-large-files
- repo: https://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-vet
    - id: go-fmt
    - id: go-lint
    - id: go-unit-tests
