version: '2'
services:
  redis:
    image: "redis:5"

  web:
    image: "pstuifzand/eksterd:alpine"
    working_dir: /opt/microsub
    links:
      - redis:redis
    volumes:
      - .:/app:ro
      - ./data:/opt/microsub
    entrypoint: /app/eksterd
    command: -auth=false -port 80 -templates /app/templates
    ports:
      - 8089:80
    environment:
      - "FEEDBIN_USER="
      - "FEEDBIN_PASS="
      - "EKSTER_BASEURL="
      - "EKSTER_TEMPLATES=/app/templates"
